from django.urls import path
from mail.apps import MailConfig
from .views import (
    HomeView,
    SendMailView,
    AddresseesListView,
    AddresseesCreateView,
    AddresseesUpdateView,
    AddresseesDeleteView,
    MessageListView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MailingListView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    MessageDetailView,
    MailingDetailView,
    AddresseesDetailView
)

app_name = MailConfig.name

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("addressees/",
         AddresseesListView.as_view(),
         name="addressees_list"),
    path("addressees/create",
         AddresseesCreateView.as_view(),
         name="addressees_create"),
    path(
        "addressees/<int:pk>/update",
        AddresseesUpdateView.as_view(),
        name="addressees_update",
    ),
    path(
        "addressees/<int:pk>/delete",
        AddresseesDeleteView.as_view(),
        name="addressees_confirm_delete",
    ),
    path(
        "addressees/detail/<int:pk>",
        AddresseesDetailView.as_view(),
        name="addressees_detail",
    ),
    path("message/",
         MessageListView.as_view(),
         name="message_list"),
    path("message/create",
         MessageCreateView.as_view(),
         name="message_create"),
    path("message/<int:pk>/update",
         MessageUpdateView.as_view(),
         name="message_update"),
    path(
        "message/<int:pk>/delete",
        MessageDeleteView.as_view(),
        name="message_confirm_delete",
    ),
    path("message/<int:pk>",
         MessageDetailView.as_view(),
         name="message_detail"),
    path("mailing/",
         MailingListView.as_view(),
         name="mailing_list"),
    path("mailing/create",
         MailingCreateView.as_view(),
         name="mailing_create"),
    path("mailing/<int:pk>/update",
         MailingUpdateView.as_view(),
         name="mailing_update"),
    path(
        "mailing/<int:pk>/delete",
        MailingDeleteView.as_view(),
        name="mailing_confirm_delete",
    ),
    path("mailing/<int:pk>",
         MailingDetailView.as_view(),
         name="mailing_detail"),
    path("send-mail/<int:mailing_id>",
         SendMailView.as_view(),
         name="send_mail"),
]
